### ISSUE TITLE
scraping needs to be updated

### ISSUE THREAD

**Issue by mvresh** [MarwanDebbiche/post-tuto-deployment#2]
source code has been updated and so the classes have changed for category objects. Code should be updated to fetch the data .

> data = {}

>soup = get_soup(base_url + '/categories')
>for category in soup.findAll('div', {'class': 'category-object'}):
>    name = category.find('h3', {'class': 'sub-category__header'}).text
>    name = name.strip()
>   data[name] = {}  
>    sub_categories = category.find('div', {'class': 'sub-category-list'})
>    for sub_category in sub_categories.findAll('div', {'class': 'child-category'}):
>        sub_category_name = sub_category.find('a', {'class': 'sub-category-item'}).text 
>        sub_category_uri = sub_category.find('a', {'class': 'sub-category-item'})['href'] 
>        data[name][sub_category_name] = sub_category_uri

**Comment by redcican** [comment]
@ahmedbesbes can you please solve this problem? I really want to follow your tutorials to build such cool app.

**Comment by ahmedbesbes** [comment]
hello @redcican 

We cannot provide support for this rn.
We'll let you know if something comes up in the near future. In the meantime, updating the code should be easy with some HTML / scraping knowledge.
